[tool.poetry]
name = "text-viewer"
version = "0.1.0"
description = ""
authors = ["widehyo@mobigen.com <widehyo@mobigen.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
textual = "^2.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
