# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "rockylinux/9"
  config.vm.box_version = "4.0.0"
  config.vm.hostname = "postgres"

  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.network "forwarded_port", guest: 5432, host: 15432

  config.vm.synced_folder "./config", "/root/config"



  config.vm.provision "shell", inline: <<-SHELL
    sh /root/config/all_in_one.sh
  SHELL
end
