[tool.poetry]
name = "pdf"
version = "0.1.0"
description = ""
authors = ["widehyo <widehyo@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
weasyprint = "^65.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
