-- \COPY geeknews_xargs (url, title, content) FROM 'bulk_data_xargs_v2.csv' WITH (FORMAT csv);
-- \COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_1024/dir_html_00/output.csv' WITH (FORMAT csv);
-- \COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_1024/dir_html_01/output.csv' WITH (FORMAT csv);
-- \COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_1024/dir_html_02/output.csv' WITH (FORMAT csv);
-- \COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_1024/dir_html_03/output.csv' WITH (FORMAT csv);
-- \COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_1024/dir_html_04/output.csv' WITH (FORMAT csv);
-- \COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_1024/dir_html_05/output.csv' WITH (FORMAT csv);
-- \COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_1024/dir_html_06/output.csv' WITH (FORMAT csv);
-- \COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_1024/dir_html_07/output.csv' WITH (FORMAT csv);
-- \COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_1024/dir_html_08/output.csv' WITH (FORMAT csv);
-- \COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_1024/dir_html_09/output.csv' WITH (FORMAT csv);
-- \COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_1024/dir_html_10/output.csv' WITH (FORMAT csv);
-- \COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_1024/dir_html_11/output.csv' WITH (FORMAT csv);
-- \COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_1024/dir_html_12/output.csv' WITH (FORMAT csv);
-- \COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_1024/dir_html_13/output.csv' WITH (FORMAT csv);
-- \COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_1024/dir_html_14/output.csv' WITH (FORMAT csv);
-- \COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_1024/dir_html_15/output.csv' WITH (FORMAT csv);
-- \COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_1024/dir_html_16/output.csv' WITH (FORMAT csv);
-- \COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_1024/dir_html_17/output.csv' WITH (FORMAT csv);
-- \COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_1024/dir_html_18/output.csv' WITH (FORMAT csv);
-- \COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_1024/dir_html_19/output.csv' WITH (FORMAT csv);
-- \COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_1024/dir_html_20/output.csv' WITH (FORMAT csv);
-- \COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_1024/dir_html_21/output.csv' WITH (FORMAT csv);


\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_00.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_01.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_02.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_03.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_04.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_05.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_06.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_07.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_08.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_09.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_10.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_11.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_12.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_13.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_14.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_15.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_16.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_17.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_18.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_19.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_20.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_21.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_22.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_23.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_24.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_25.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_26.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_27.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_28.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_29.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_30.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_31.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_32.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_33.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_34.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_35.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_36.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_37.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_38.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_39.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_40.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_41.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_42.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_43.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_44.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_45.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_46.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_47.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_48.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_49.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_50.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_51.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_52.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_53.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_54.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_55.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_56.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_57.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_58.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_59.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_60.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_61.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_62.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_63.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_64.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_65.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_66.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_67.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_68.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_69.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_70.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_71.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_72.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_73.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_74.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_75.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_76.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_77.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_78.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_79.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_80.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_81.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_82.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_83.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_84.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_85.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_86.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_87.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_88.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_89.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9000.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9001.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9002.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9003.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9004.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9005.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9006.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9007.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9008.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9009.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9010.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9011.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9012.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9013.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9014.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9015.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9016.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9017.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9018.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9019.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9020.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9021.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9022.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9023.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9024.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9025.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9026.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9027.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9028.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9029.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9030.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9031.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9032.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9033.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9034.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9035.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9036.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9037.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9038.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9039.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9040.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9041.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9042.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9043.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9044.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9045.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9046.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9047.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9048.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9049.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9050.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9051.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9052.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9053.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9054.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9055.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9056.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9057.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9058.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9059.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9060.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9061.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9062.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9063.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9064.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9065.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9066.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9067.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9068.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9069.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9070.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9071.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9072.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9073.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9074.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9075.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9076.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9077.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9078.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9079.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9080.csv' WITH (FORMAT csv);
\COPY geeknews_xargs (url, title, content) FROM 'split_workspace/sp_128/output_9081.csv' WITH (FORMAT csv);
